import { describe, it, expect, afterAll } from 'vitest';
import { ImapConnection } from '../src/imap/connection';

const EMAIL = process.env.TEST_IMAP_EMAIL;
const PASSWORD = process.env.TEST_IMAP_PASSWORD;
const maybe = EMAIL && PASSWORD ? describe : describe.skip;

maybe('ImapConnection (live Gmail)', () => {
  const connection = new ImapConnection({
    id: 'test', email: EMAIL!, appPassword: PASSWORD!, isPrimary: true,
  });
  afterAll(async () => { await connection.disconnect(); });

  it('connects and authenticates', async () => {
    await connection.connect();
    expect(connection.isConnected).toBe(true);
  }, 30_000);

  it('lists mailboxes including INBOX', async () => {
    const boxes = await connection.listMailboxes();
    expect(boxes.some((b) => b.path.toUpperCase() === 'INBOX')).toBe(true);
  }, 30_000);

  it('reports special-use attributes, which is what folder discovery matches on', async () => {
    // The one assertion in this file that cannot be made against a fixture:
    // that a REAL Gmail account actually reports \Sent/\Junk/\Trash through
    // imapflow's `specialUse`. tests/folders.test.ts proves discovery reads
    // that field correctly; this proves the field is really there to read.
    const boxes = await connection.listMailboxes();
    const attributes = boxes.map((b) => b.specialUse);

    expect(attributes).toContain('\\Sent');
    expect(attributes).toContain('\\Junk');
    expect(attributes).toContain('\\Trash');
  }, 30_000);

  it('opens INBOX and reports uidValidity and uidNext', async () => {
    const info = await connection.openMailbox('INBOX');
    expect(info.path.toUpperCase()).toBe('INBOX');
    expect(info.uidValidity).toBeGreaterThan(0n);
    expect(info.uidNext).toBeGreaterThan(0n);

    // The two assertions above pass even if uidValidity and uidNext were
    // swapped when MailboxInfo was built, since both happen to be positive
    // on a real mailbox. To actually catch a swap, cross-check against an
    // independent STATUS call, which reads the same server state through
    // a different code path than openMailbox()'s field mapping. A swap bug
    // would make info.uidValidity equal the *wrong* one of the two
    // server-reported values, which — unlike "both are positive" — is not
    // something a swap could accidentally satisfy: uidValidity and uidNext
    // are generated by unrelated mechanisms on the server, so they are
    // extremely unlikely to collide.
    const status = await connection.rawClient().status('INBOX', { uidValidity: true, uidNext: true });
    expect(info.uidValidity).toBe(status.uidValidity);
    expect(info.uidNext).toBe(BigInt(status.uidNext ?? -1));
  }, 30_000);

  it('rejects a bad password without leaking it in the error', async () => {
    const bad = new ImapConnection({
      id: 'bad', email: EMAIL!, appPassword: 'wrongwrongwrong1', isPrimary: false,
    });
    await expect(bad.connect()).rejects.toThrow();
    try { await bad.connect(); } catch (error) {
      expect(String(error)).not.toContain('wrongwrongwrong1');
    }
  }, 30_000);
});
